# Generated by Django 5.1.2 on 2026-05-06 10:17

from django.db import migrations


def create_test_data(apps, schema_editor):
    Category = apps.get_model('main', 'Category')
    Product = apps.get_model('main', 'Product')
    
    # Create 5 categories
    categories = [
        Category(name='Elektronika', is_active=True),
        Category(name='Kiyimlar', is_active=True),
        Category(name='Oziq-ovqat', is_active=True),
        Category(name='Maishiy texnika', is_active=True),
        Category(name='Kitoblar', is_active=True),
    ]
    
    # Save categories
    for category in categories:
        category.save()
    
    # Create 6 products
    products = [
        {
            'name': 'Smartphone Samsung Galaxy',
            'description': 'Zamonaviy smartfon yuqori texnologiyalar bilan',
            'price': 2500.00,
            'discount_price': 2200.00,
            'discount_status': True,
            'count': 15,
            'category': categories[0]
        },
        {
            'name': 'Laptop HP Pavilion',
            'description': 'Kuchaytirilgan ishlash uchun noutbuk',
            'price': 5500.00,
            'discount_price': None,
            'discount_status': False,
            'count': 8,
            'category': categories[0]
        },
        {
            'name': 'Erkaklar koylaki',
            'description': 'Qishki mavsum uchun issiq koylak',
            'price': 150.00,
            'discount_price': 120.00,
            'discount_status': True,
            'count': 25,
            'category': categories[1]
        },
        {
            'name': 'Muzlatgichi Samsung',
            'description': 'Katta hajmli muzlatgich',
            'price': 3200.00,
            'discount_price': None,
            'discount_status': False,
            'count': 5,
            'category': categories[3]
        },
        {
            'name': 'Qozon to\'plami',
            'description': 'Turli o\'lchamdagi qozonlar to\'plami',
            'price': 200.00,
            'discount_price': 180.00,
            'discount_status': True,
            'count': 30,
            'category': categories[3]
        },
        {
            'name': 'Dasturlash kitobi',
            'description': 'Python dasturlash tili uchun qo\'llanma',
            'price': 80.00,
            'discount_price': None,
            'discount_status': False,
            'count': 50,
            'category': categories[4]
        },
    ]
    
    # Save products
    for product_data in products:
        product = Product(**product_data)
        product.save()


def remove_test_data(apps, schema_editor):
    Category = apps.get_model('main', 'Category')
    Product = apps.get_model('main', 'Product')
    
    # Delete all test products
    Product.objects.all().delete()
    
    # Delete all test categories
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_banner_id_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RunPython(create_test_data, remove_test_data),
    ]
