# Generated by Django 5.1.2 on 2026-05-06 10:44

from django.db import migrations
from django.core.files import File
import os


def add_images_to_categories_and_products(apps, schema_editor):
    Category = apps.get_model('main', 'Category')
    Product = apps.get_model('main', 'Product')
    
    # Add images to categories
    categories_mapping = {
        'Elektronika': 'smart2010.png',
        'Kiyimlar': 'hobbi2110.png',
        'Oziq-ovqat': 'image_2026-04-27_10-20-39.png',
        'Maishiy texnika': 'download.png',
        'Kitoblar': 'i.webp'
    }
    
    for category_name, image_name in categories_mapping.items():
        try:
            category = Category.objects.get(name=category_name)
            image_path = f'media/categories/{image_name}'
            if os.path.exists(image_path):
                with open(image_path, 'rb') as f:
                    category.logo.save(image_name, File(f), save=True)
        except Category.DoesNotExist:
            continue
    
    # Add images to products
    products_mapping = {
        'Smartphone Samsung Galaxy': 'smart2010.png',
        'Laptop HP Pavilion': 'img_3.jpg',
        'Erkaklar koylaki': 'photo_2026-04-21_16.44.00.jpeg',
        'Muzlatgichi Samsung': 'img_4.jpg',
        'Qozon to\'plami': 'photo_2026-04-21_16.52.59.jpeg',
        'Dasturlash kitobi': 'download_1.jpeg'
    }
    
    for product_name, image_name in products_mapping.items():
        try:
            product = Product.objects.get(name=product_name)
            image_path = f'media/products/{image_name}'
            if os.path.exists(image_path):
                with open(image_path, 'rb') as f:
                    product.image.save(image_name, File(f), save=True)
        except Product.DoesNotExist:
            continue


def remove_images_from_categories_and_products(apps, schema_editor):
    Category = apps.get_model('main', 'Category')
    Product = apps.get_model('main', 'Product')
    
    # Remove images from categories
    for category in Category.objects.all():
        if category.logo:
            category.logo.delete()
    
    # Remove images from products
    for product in Product.objects.all():
        if product.image:
            product.image.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_banner_id_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RunPython(add_images_to_categories_and_products, remove_images_from_categories_and_products),
    ]
